# name: CI/CD to Huawei SWR and CCE

# on:
#   push:
#     branches:
#       - main  # Trigger CI/CD when code is pushed to the 'master' branches

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Get CCE Cluster Credentials
#         uses: huaweicloud/cce-credential-action@v1.0.1
#         with:
#           ak: ${{ secrets.ACCESSKEY }}
#           sk: ${{ secrets.SECRETACCESSKEY }}
#           region: "af-south-1"
#           project_id: "eecc7ec81ad346adbcde0a07fa343cb0"
#           cluster_id: "36aae077-e83f-11ee-b54e-0255ac100750"

#       - name: Get CCE Cluster info
#         run: |
#           kubectl version --client 
#           kubectl cluster-info

name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - main  # Trigger CI/CD when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Uninstall kubectl (optional)
        run: |
          sudo apt remove kubectl -y  

      - name: Install kubectl 1.27
        run: |
          curl -LO https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/  # Adjust path if needed for your environment
          
      - name: Get CCE Cluster Credentials
        uses: huaweicloud/cce-credential-action@v1.0.0
        with:
          ak: ${{ secrets.ACCESSKEY }}
          sk: ${{ secrets.SECRETACCESSKEY }}
          region: "af-south-1"
          project_id: "eecc7ec81ad346adbcde0a07fa343cb0"
          cluster_id: "36aae077-e83f-11ee-b54e-0255ac100750"

      - name: Get CCE Cluster info
        run: |
          kubectl cluster-info

 

      - name: Get CCE Cluster info
        run: |
          kubectl cluster-info
